// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace SampleApiClient.Models
{
    public partial class FeedItem
    {
        private string _content;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Content
        {
            get { return this._content; }
            set { this._content = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _link;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Link
        {
            get { return this._link; }
            set { this._link = value; }
        }
        
        private DateTimeOffset? _publishDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? PublishDate
        {
            get { return this._publishDate; }
            set { this._publishDate = value; }
        }
        
        private string _title;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Title
        {
            get { return this._title; }
            set { this._title = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FeedItem class.
        /// </summary>
        public FeedItem()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken contentValue = inputObject["Content"];
                if (contentValue != null && contentValue.Type != JTokenType.Null)
                {
                    this.Content = ((string)contentValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken linkValue = inputObject["Link"];
                if (linkValue != null && linkValue.Type != JTokenType.Null)
                {
                    this.Link = ((string)linkValue);
                }
                JToken publishDateValue = inputObject["PublishDate"];
                if (publishDateValue != null && publishDateValue.Type != JTokenType.Null)
                {
                    this.PublishDate = ((DateTimeOffset)publishDateValue);
                }
                JToken titleValue = inputObject["Title"];
                if (titleValue != null && titleValue.Type != JTokenType.Null)
                {
                    this.Title = ((string)titleValue);
                }
            }
        }
    }
}
