// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;
using SampleApiClient;
using SampleApiClient.Models;

namespace SampleApiClient
{
    public static partial class NewsExtensions
    {
        /// <param name='operations'>
        /// Reference to the SampleApiClient.INews.
        /// </param>
        public static IList<FeedItem> Get(this INews operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((INews)s).GetAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the SampleApiClient.INews.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<FeedItem>> GetAsync(this INews operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<SampleApiClient.Models.FeedItem>> result = await operations.GetWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the SampleApiClient.INews.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        public static FeedItem GetById(this INews operations, int id)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((INews)s).GetByIdAsync(id);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the SampleApiClient.INews.
        /// </param>
        /// <param name='id'>
        /// Required.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<FeedItem> GetByIdAsync(this INews operations, int id, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<SampleApiClient.Models.FeedItem> result = await operations.GetByIdWithOperationResponseAsync(id, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
