// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SampleApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FeedItem
    {
        /// <summary>
        /// Initializes a new instance of the FeedItem class.
        /// </summary>
        public FeedItem() { }

        /// <summary>
        /// Initializes a new instance of the FeedItem class.
        /// </summary>
        public FeedItem(int? id = default(int?), string title = default(string), string description = default(string), string link = default(string), string content = default(string), DateTime? publishDate = default(DateTime?))
        {
            Id = id;
            Title = title;
            Description = description;
            Link = link;
            Content = content;
            PublishDate = publishDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "link")]
        public string Link { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "content")]
        public string Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publishDate")]
        public DateTime? PublishDate { get; set; }

    }
}
